config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "cocktails#index"
  resources :cocktails, except: [:edit, :update, :destroy] do
    resources :doses, only: [:new, :create]
  end

  resources :doses, only: [:destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates_uniqueness_of :cocktail_id, scope: :ingredient_id
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, uniqueness: true, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :find_cocktail, only: [:show, :update]

  def index
    @cocktails = Cocktail.all
  end

  def show
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.create(cocktail_params)
    redirect_to cocktails_path
  end

  def new
    @cocktail = Cocktail.new
  end

  def update
  end

  private

  def find_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :find_cocktail, only: [:index, :show, :create, :new]
  before_action :find_dose, only: [:destroy]

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
     if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def new
    @dose = Dose.new
  end

  def update
  end

  def destroy
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def find_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def find_dose
    @dose = Dose.find(params[:id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for @cocktail do |c| %>
  <%= c.input :name %>
  <%= c.submit %>
  <%= link_to "Cancel", cocktails_path, class: 'btn-g'%>
<%end%>

app/views/cocktails/index.html.erb
<div class="wrapper">
  <div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.5) 0%, rgba(0,0,0,0.6) 50%), url('https://static.pexels.com/photos/4784/alcohol-bar-party-cocktail.jpg');">
    <div class="banner-content">

     <h1>The Best Cocktails</h1>

     <% @cocktails.each do |cocktail| %>

     <p><%= link_to cocktail.name, cocktail_path(cocktail), class: "btn-g" %></p>
     <% end %>

     <p><%= link_to "Add a cocktail", new_cocktail_path, class: "btn-g-2" %></p>

   </div>
 </div>
</div>
ß

app/views/cocktails/new.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.5) 0%, rgba(0,0,0,0.6) 50%), url('https://static.pexels.com/photos/4295/black-and-white-alcohol-bar-drinks.jpg');">
<div class="banner-content" class='form'>
    <div class="container">
      <div class="row">
        <div class="col-xs-4 col-xs-offset-7">
          <h2>Add a new cocktail</h2>

          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
  <div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.5) 0%, rgba(0,0,0,0.6) 50%), url('https://static.pexels.com/photos/4295/black-and-white-alcohol-bar-drinks.jpg');">
    <div class="banner-content">
      <h1><%= @cocktail.name %></h1>

      <ul>
        <% @cocktail.doses.each do |dose| %>
        <ul class='list-inline'><li><%= dose.ingredient.name %> - <%= dose.description %></li>
        <%= link_to "Delete", dose_path(dose), method: :delete %></ul>
        <% end %>
        <div class="form">
         <div class="container">
          <div class="row">
            <div class="col-xs-3 col-xs-offset-7">
              <%= simple_form_for [@cocktail, @dose] do |d| %>
                <%= d.input :ingredient_id, collection: Ingredient.all %>
                <%= d.input :description, placeholder: '20ml' %>
                <%= d.submit %>
              <%end%>
            </div>
          </div>
         </div>
        </div>
      </ul>

      <p><%= link_to "Return to cocktails", cocktails_path(@cocktail), class: "btn-g" %></p>
    </div>
  </div>

app/views/cocktails/update.html.erb
<h1>Cocktails#update</h1>
<p>Find me in app/views/cocktails/update.html.erb</p>

app/views/doses/index.html.erb
<h1>Doses#index</h1>
<p>Find me in app/views/doses/index.html.erb</p>

app/views/doses/new.html.erb
<div class="wrapper">
  <div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.5) 0%, rgba(0,0,0,0.6) 50%), url('https://static.pexels.com/photos/4784/alcohol-bar-party-cocktail.jpg');">
    <div class="banner-content">
      <h1>Add ingredient</h1>

      <div class="container">
        <%= simple_form_for [@cocktail, @dose] do |d| %>
          <%= d.input :ingredient_id, collection: Ingredient.all %>
          <%= d.input :description %>

          <%= d.submit %>
          <%end%>
      </div>
    </div>
  </div>
</div>

app/views/doses/show.html.erb
<h1>Doses#show</h1>
<p>Find me in app/views/doses/show.html.erb</p>

app/views/doses/update.html.erb
<h1>Doses#update</h1>
<p>Find me in app/views/doses/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsMisterCocktail</title>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'shared/navbar' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "cocktail_icon.jpg" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to "Add a cocktail", new_cocktail_path, class: "btn-g-3" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>